# Generated by Django 5.2.7 on 2025-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_html', models.TextField()),
                ('content_text', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
